### ISSUE TITLE
Does not comply with psr-4 autoloading

### ISSUE THREAD

**Issue by MaximilianRadons** [dpdconnect/php-sdk#13]
File /src\Api\Data\ShipmentOrder\Customs\CustomsLinesInterface.php does not comply with psr-4 autoloading standard.
The namespace is wrong:
```
namespace DpdConnect\Sdk\Api\Data\ShipmentOrder;
```
Needs to be changed to:
```
namespace DpdConnect\Sdk\Api\Data\ShipmentOrder\Customs;
```
Greetings Max

**Comment by RickDBCN** [comment]
@dpdplugin can we move this forward? we are experiencing the same issue.

**Comment by dpdplugin** [comment]
Fixed in the latest release.
