### ISSUE TITLE
Error: Call to a member function getCachedList() on null

### ISSUE THREAD

**Issue by yaroslav-qlicks** [dpdconnect/php-sdk#19]
Fatal error on /checkout/cart/

![image](https://user-images.githubusercontent.com/80677410/198533551-6a519c46-7ce6-44d5-a28a-afc90d510f19.png)

**Comment by dpdplugin** [comment]
Hi Yaroslav,

I see you are opening an issue in the repo of the PHP SDK for an issue with the Magento 2 module.
You are using the latest version of the SDK with the Magento 2 module, as defined in the composer.json they aren't compatible yet.
Please install the Magento module using composer or use version 1.1.8 if you got it installed in the app/code folder.

**Comment by yaroslav-qlicks** [comment]
> You are using the latest version of the SDK with the Magento 2 module, as defined in the composer.json they aren't compatible yet.
@dpdplugin I understand. But in this case php-sdk should be released with version 2.x or dependency in magento2 module should be changed
Because you released uncompatible version just with patch change (semantic versioning) and IMHO this is not good
