### ISSUE TITLE
Kan plugin woocommerce niet activeren

### ISSUE THREAD

**Issue by giuvinti** [dpdconnect/php-sdk#5]
Wat doe ik mis?

Plugin kan niet worden geactiveerd omdat hij een fatale fout veroorzaakt.

Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in /home/u86682p81443/domains/pokemart.be/public_html/wp-content/plugins/woocommerce-shipping-master/dpdconnect.php on line 3

Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='.:/opt/alt/php70/usr/share/pear') in /home/u86682p81443/domains/pokemart.be/public_html/wp-content/plugins/woocommerce-shipping-master/dpdconnect.php on line 3

**Comment by dpdplugin** [comment]
Please download the plugin from the releases page instead of the green download code button
