### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by shalinikat** [dpdconnect/php-sdk#6]
{"0":"{\"code\":401,\"message\":\"Bad credentials\"}","1":"#1 DpdConnect\\Sdk\\Resources\\Authentication->authenticate(array('username' => '**username**', 'password' => '**password**')) called at [app\/code\/DpdConnect\/Sdk\/Resources\/Authentication.php:33]\n#2 
What will be the username and password used in php sdk authentication?

**Comment by dpdplugin** [comment]
Bad credentials means that not the correct credentials are used, please look in the readme for examples
